# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RzvZ0AJjjT8LSzNhWBiaw2vGBCRLqrlI
"""

import numpy as np
from cvxopt import matrix,solvers

Xo=np.asarray([[1,0.5,0.5],[1,0.5,1.0],[1,1,1.5],[1,1.5,0.5],[1,1.5,2.0],[1,2.0,1.0],\
   [1,2.5,2.0],[1,2.5,2.5]])
D=np.asarray([[-1,-1,-1,-1,1,1,1,1]])

X=D.T*Xo
P=matrix(X.dot(X.T))
q=matrix([-1.]*8)
h=matrix(8*[0.0])
G=matrix(-1.*np.eye(8))
r=solvers.qp(P,q,G,h)
lm=np.asarray(r['x'])
ld=(lm.T*D).T
W=np.asarray([1]*8).T.dot(ld*Xo)

import matplotlib.pyplot as plt
x1=np.arange(-1,5,0.1)
x2=-W[0]/W[2]-W[1]*x1/W[2]
fig, ax = plt.subplots()
ax.plot(x1,x2,'r')
ax.plot(Xo[0:4,1],Xo[0:4,2],'.')
ax.plot(Xo[4:8,1],Xo[4:8,2],'+')
# ax.set_aspect('equal')
ax.grid(True, which='both')
ax.axhline(y=0, color='k')
ax.axvline(x=0, color='k')
plt.xticks(np.arange(min(x1), max(x1)+1, 1.0))
plt.show()

print(P)

print(lm)
print(ld)
print(np.sum(ld))
print(W)

import numpy as np
from cvxopt import matrix,solvers

Xo=np.asarray([[1,0,0],[1,0,1.0],[1,1,0],[1,1,1]])
D=np.asarray([[-1,-1,-1,1]])

X=D.T*Xo
P=matrix(X.dot(X.T))
q=matrix([-1.]*4)
h=matrix(4*[0.0])
G=matrix(-1.*np.eye(4))
r=solvers.qp(P,q,G,h)
lm=np.asarray(r['x'])
ld=(lm.T*D).T
W=np.asarray([1]*4).T.dot(ld*Xo)

import matplotlib.pyplot as plt
x1=np.arange(-1,5,0.1)
x2=-W[0]/W[2]-W[1]*x1/W[2]
fig, ax = plt.subplots()
ax.plot(x1,x2,'r')
ax.plot(Xo[0:3,1],Xo[0:3,2],'o')
ax.plot(Xo[3:4,1],Xo[3:4,2],'+')
# ax.set_aspect('equal')
ax.grid(True, which='both')
ax.axhline(y=0, color='k')
ax.axvline(x=0, color='k')
plt.xticks(np.arange(min(x1), max(x1)+1, 1.0))
plt.show()

