# -*- coding: utf-8 -*-
"""Backpropagation (12 Examples).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ht3d8o9SLDT894OzA1BGCXGpABi99WWd
"""

import numpy as np

def feed_forward(hidden_layer,output_layer,x):
    y = np.dot(hidden_layer,x)
    y = np.append(np.asarray([1]),1/(1+np.exp(-y)))
    o = np.dot(output_layer,y)
    o = 1/(1+np.exp(-o))
    return y,o

def feed_forward_output(hidden_layer,output_layer,x):
    y,o = feed_forward(hidden_layer,output_layer,x)
    return o

hidden_nodes = 4
output_nodes = 1
input_nodes = 2
max_iter = 100000
eta = 0.1
output_layer = np.asarray([np.random.rand(hidden_nodes+1) for i in range(output_nodes)])-0.5
hidden_layer = np.asarray([np.random.rand(input_nodes+1) for i in range(hidden_nodes)])-0.5
print(output_layer)
print(hidden_layer)

print(output_layer)
print(hidden_layer)

x = np.asarray([[1,0,2],[1,2,0],[1,2,4],[1,4,2],[1,1,1],[1,1,3],[1,3,1],[1,3,3],[1,1,2],[1,2,1],[1,2,3],[1,3,2]])
# d = np.asarray([[0,1],[1,0],[1,0],[0,1]])
d = np.asarray([[1],[1],[1],[1],[1],[1],[1],[1],[0],[0],[0],[0]])
d = np.ones_like(d)-d
q = len(x)

x

x[:,1]

import matplotlib.pyplot as plt

plt.plot(x[:8,1],x[:8,2],'g.')
plt.plot(x[8:,1],x[8:,2],'r.')

err_list = [0]*max_iter
run_iter = 0
weight_save = []
for iter in range(max_iter):
    err = 0
    for j in range(q):
        # forward input to hidden
        y,o = feed_forward(hidden_layer,output_layer,x[j])
        delta_k = o*(1-o)*(d[j]-o)
        delta_h = y*(1-y)*(output_layer.T.dot(delta_k))
        delta_h = delta_h[1:]
        # update output layer
        delta_wo = eta * np.matrix(delta_k).T * np.matrix(y)
        delta_wh = eta * np.matrix(delta_h).T * np.matrix(x[j])
        hidden_layer += delta_wh
        output_layer += delta_wo
        e = o - d[j]
        err += e.dot(e)
        err_list[iter] = err
        run_iter += 1
        if(run_iter % 5000 == 0):
            weight_save.append(tuple((hidden_layer*1.0,output_layer*1.0)))
    if err < 1e-3:
        break

print('Error =',err,'in iteration',run_iter)
print(output_layer)
print(hidden_layer)

import matplotlib.pyplot as plt
t = np.arange(0,100000,1)
plt.plot(t[:run_iter],err_list[:run_iter],'b')
plt.show()

from mpl_toolkits.mplot3d import axes3d

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
X = np.arange(0,4,0.05)
Y = np.arange(0,4,0.05)
X,Y = np.meshgrid(X,Y)
zs = np.array([feed_forward_output(hidden_layer,output_layer,np.asarray([1,x,y])) for x,y in zip(np.ravel(X), np.ravel(Y))])
Z = zs.reshape(X.shape)
ax.plot_wireframe(X, Y, Z, rstride=1, cstride=1)
X1 = np.arange(0,4,0.01)
for i in range(len(hidden_layer)):
    Yi = (-hidden_layer[i][0] - hidden_layer[i][1]*X1)/hidden_layer[i][2]
    ax.plot(X1, Yi, zs=0, zdir='z', label='zs=0, zdir=z',c='g')
plt.show()

from mpl_toolkits.mplot3d import axes3d
import math


fig2 = plt.figure(figsize=(5,40))
X = np.arange(0,4,0.05)
Y = np.arange(0,4,0.05)
X,Y = np.meshgrid(X,Y)

rows = math.ceil(len(weight_save)/3)
for i,j in [(i,j) for i in range(rows) for j in range(3)]:
    if(i*3+j) >= len(weight_save):
        break
    zs = np.array([feed_forward_output(weight_save[i*3+j][0],weight_save[i*3+j][1],np.asarray([1,x,y])) for x,y in zip(np.ravel(X), np.ravel(Y))])
    Z = zs.reshape(X.shape)
    ax = fig2.add_subplot(rows,3,(i*3)+j+1, projection='3d')
    ax.plot_wireframe(X, Y, Z, rstride=1, cstride=1)

plt.show()