# -*- coding: utf-8 -*-
"""Backpropagation XOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AIba_sQeZJRCFl5LX-FquJp97O6oNFIE
"""

import numpy as np

def feed_forward(hidden_layer,output_layer,x):
    y = np.dot(hidden_layer,x)
    y = np.append(np.asarray([1]),1/(1+np.exp(-y)))
    o = np.dot(output_layer,y)
    o = 1/(1+np.exp(-o))
    return y,o

def feed_forward_output(hidden_layer,output_layer,x):
    y,o = feed_forward(hidden_layer,output_layer,x)
    return o

hidden_nodes = 2
output_nodes = 1
input_nodes = 2
max_iter = 100000
eta = 0.1
output_layer = np.asarray([np.random.rand(hidden_nodes+1) for i in range(output_nodes)])-0.5
hidden_layer = np.asarray([np.random.rand(input_nodes+1) for i in range(hidden_nodes)])-0.5
print(output_layer)
print(hidden_layer)

x = np.asarray([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
# d = np.asarray([[0,1],[1,0],[1,0],[0,1]])
d = np.asarray([[0],[1],[1],[0]])
q = len(x)

err_list = [0]*max_iter
run_iter = 0
weight_save = []
for iter in range(max_iter):
    err = 0
    for j in range(q):
        # forward input to hidden
        y,o = feed_forward(hidden_layer,output_layer,x[j])
        delta_k = o*(1-o)*(d[j]-o)
        delta_h = y*(1-y)*(output_layer.T.dot(delta_k))
        delta_h = delta_h[1:]
        # update output layer
        delta_wo = eta * np.matrix(delta_k).T * np.matrix(y)
        delta_wh = eta * np.matrix(delta_h).T * np.matrix(x[j])
        hidden_layer += delta_wh
        output_layer += delta_wo
        e = o - d[j]
        err += e.dot(e)
        err_list[iter] = err
        run_iter += 1
        if(run_iter % 5000 == 0):
            weight_save.append(tuple((hidden_layer*1.0,output_layer*1.0)))
    if err < 1e-2:
        break

print('Error =',err,'in iteration',run_iter)
print(output_layer)
print(hidden_layer)

"""```
W0X0+W1X1+W2X2=0
W0+W1X+W2Y=0
Y=(-W1/W2)X-W0/W2
```


"""

import matplotlib.pyplot as plt

w=hidden_layer
x_show=np.arange(-0.5,1.5,0.1)
y_show=-w[0][1]/w[0][2]*x_show-w[0][0]/w[0][2]
plt.plot(x_show,y_show,'g')
y_show=-w[1][1]/w[1][2]*x_show-w[1][0]/w[1][2]
plt.plot(x_show,y_show,'g')
plt.plot([0,1],[0,1],'r.')
plt.plot([0,1],[1,0],'g.')

import matplotlib.pyplot as plt
t = np.arange(0,100000,1)
plt.plot(t[:run_iter],err_list[:run_iter],'b')
plt.show()

from mpl_toolkits.mplot3d import axes3d

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
X = np.arange(0,1,0.01)
Y = np.arange(0,1,0.01)
X,Y = np.meshgrid(X,Y)
zs = np.array([feed_forward_output(hidden_layer,output_layer,np.asarray([1,x,y])) for x,y in zip(np.ravel(X), np.ravel(Y))])
Z = zs.reshape(X.shape)
ax.plot_wireframe(X, Y, Z, rstride=1, cstride=1)
X1 = np.arange(0,1,0.01)
for i in range(len(hidden_layer)):
    Yi = (-hidden_layer[i][0] - hidden_layer[i][1]*X1)/hidden_layer[i][2]
    ax.plot(X1, Yi, zs=0, zdir='z', label='zs=0, zdir=z',c='g')
plt.show()