# -*- coding: utf-8 -*-
"""Movement of Sigmoid Hyperplane in Backpropagation XOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQn-hHY6J0YO_hI0qDplxXdBmlRYmi8D
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation

def feed_forward(hidden_layer,output_layer,x):
    y = np.dot(hidden_layer,x)
    y = np.append(np.asarray([1]),1/(1+np.exp(-y)))
    o = np.dot(output_layer,y)
    o = 1/(1+np.exp(-o))
    return y,o

def feed_forward_output(hidden_layer,output_layer,x):
    y,o = feed_forward(hidden_layer,output_layer,x)
    return o

hidden_nodes = 2
output_nodes = 1
input_nodes = 2
max_iter = 100000
eta = 0.1
output_layer = np.asarray([np.random.rand(hidden_nodes+1) for i in range(output_nodes)])-0.5
hidden_layer = np.asarray([np.random.rand(input_nodes+1) for i in range(hidden_nodes)])-0.5
print(output_layer)
print(hidden_layer)

print(output_layer)
print(hidden_layer)

x = np.asarray([[1,0,0],[1,0,1],[1,1,0],[1,1,1]])
# d = np.asarray([[0,1],[1,0],[1,0],[0,1]])
d = np.asarray([[0],[1],[1],[0]])
q = len(x)

err_list = [0]*max_iter
run_iter = 0
weight_save = []

plt.show()
all_plots=[]

for iter in range(max_iter):
    err = 0
    for j in range(q):
        # forward input to hidden
        y,o = feed_forward(hidden_layer,output_layer,x[j])
        delta_k = o*(1-o)*(d[j]-o)
        delta_h = y*(1-y)*(output_layer.T.dot(delta_k))
        delta_h = delta_h[1:]
        # update output layer
        delta_wo = eta * np.matrix(delta_k).T * np.matrix(y)
        delta_wh = eta * np.matrix(delta_h).T * np.matrix(x[j])
        hidden_layer += delta_wh
        output_layer += delta_wo
        e = o - d[j]
        err += e.dot(e)
        err_list[iter] = err
        run_iter += 1
        if(run_iter % 5000 == 0):
            weight_save.append(tuple((hidden_layer*1.0,output_layer*1.0)))
        if(run_iter % 500 == 0):
            lines=[]
            X1 = np.arange(0,1,0.01)
            for i in range(hidden_nodes):
              Yi = (-hidden_layer[i][0] - hidden_layer[i][1]*X1)/hidden_layer[i][2]
              lines.append((X1, Yi))
            all_plots.append(lines)
    if err < 1e-2:
        break

print(len(all_plots))
fig = plt.figure()
ax = plt.axes(xlim=(-1, 2), ylim=(-1, 2))
lines = [ax.plot([], [], lw=1)[0] for i in range(len(hidden_layer))]
marks = [ax.plot([0,1],[0,1],'r.')[0]]+[ax.plot([0,1],[1,0],'g.')]

def init():
  global lines
  global marks
  for line in lines:
    line.set_data([], [])
  return lines+marks

def animate(i):
  global lines
  global marks
  [lines[j].set_data(all_plots[i][j][0], all_plots[i][j][1]) for j in range(hidden_nodes)]
  return lines+marks

anim = animation.FuncAnimation(fig, animate, init_func=init,
                               frames=len(all_plots),interval=400)

# save the animation as an mp4.  This requires ffmpeg or mencoder to be
# installed.  The extra_args ensure that the x264 codec is used, so that
# the video can be embedded in html5.  You may need to adjust this for
# your system: for more information, see
# http://matplotlib.sourceforge.net/api/animation_api.html
anim.save('basic_animation.mp4', fps=30, extra_args=['-vcodec', 'libx264'])

fig = plt.figure()
ax = plt.axes(xlim=(-1, 2), ylim=(-1, 2))
lines=[ax.plot([], [], lw=1)[0] for i in range(2)]
[lines[i].set_data(all_plots[i*100][0][0],all_plots[i*100][0][1]) for i in range(2)]
plt.show()

all_plots[0][0]

import numpy as np
from matplotlib import pyplot as plt
from matplotlib import animation

# First set up the figure, the axis, and the plot element we want to animate
fig = plt.figure()
ax = plt.axes(xlim=(0, 2), ylim=(-2, 2))
line, = ax.plot([], [], lw=2)

# initialization function: plot the background of each frame
def init():
    line.set_data([], [])
    return line,

# animation function.  This is called sequentially
def animate(i):
    x = np.linspace(0, 2, 1000)
    y = np.sin(2 * np.pi * (x - 0.01 * i))
    line.set_data(x, y)
    return line,

# call the animator.  blit=True means only re-draw the parts that have changed.

print('Error =',err,'in iteration',run_iter)
print(output_layer)
print(hidden_layer)

import matplotlib.pyplot as plt
t = np.arange(0,100000,1)
plt.plot(t[:run_iter],err_list[:run_iter],'b')
plt.show()

from mpl_toolkits.mplot3d import axes3d

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
X = np.arange(0,1,0.01)
Y = np.arange(0,1,0.01)
X,Y = np.meshgrid(X,Y)
zs = np.array([feed_forward_output(hidden_layer,output_layer,np.asarray([1,x,y])) for x,y in zip(np.ravel(X), np.ravel(Y))])
Z = zs.reshape(X.shape)
ax.plot_wireframe(X, Y, Z, rstride=1, cstride=1)
X1 = np.arange(0,1,0.01)
for i in range(len(hidden_layer)):
    Yi = (-hidden_layer[i][0] - hidden_layer[i][1]*X1)/hidden_layer[i][2]
    ax.plot(X1, Yi, zs=0, zdir='z', label='zs=0, zdir=z',c='g')
plt.show()

